name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Install Hexo CLI
        run: pnpm add -g hexo-cli
      - name: Install NexT Theme
        run: pnpm install hexo-theme-next
      - name: Generate site
        run: hexo g
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # The branch the action should deploy to.
          publish_dir: ./public # The folder the action should deploy.
          cname: hexo.ddmtdxw.top # 改成你自己的域名
